"""add salary column in employee table

Revision ID: e1080d0fd3ac
Revises: 
Create Date: 2026-08-06 16:40:04.710258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1080d0fd3ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeeDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeeDetails_id'), 'employeeDetails', ['id'], unique=False)
    op.drop_index(op.f('id'), table_name='employee_details')
    op.drop_table('employee_details')
    op.drop_index(op.f('ix_employeeDetails_id'), table_name='employeedetails')
    op.drop_table('employeedetails')
    op.drop_index(op.f('id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('salary', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id'), 'employees', ['id'], unique=True)
    op.create_table('departments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('department_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id'), 'departments', ['id'], unique=True)
    op.create_table('employeedetails',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('branch', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('designation', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employeeDetails_id'), 'employeedetails', ['id'], unique=False)
    op.create_table('employee_details',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('salary', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('employee_details_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id'), 'employee_details', ['id'], unique=True)
    op.drop_index(op.f('ix_employeeDetails_id'), table_name='employeeDetails')
    op.drop_table('employeeDetails')
    # ### end Alembic commands ###
